#!/usr/bin/env python
# -*- coding: utf-8 -*-
# Copyright (C) 2012 Ludia Inc.
# This software is licensed as described in the file LICENSE, which
# you should have received as part of this distribution.
# Author: Pior Bastida <pbastida@socialludia.com>

import pkg_resources

from argh import ArghParser

from awstools.commands import cloudformation


HELP_CFG = "path of an alternative configuration file"
HELP_SETTINGS = "path of the application settings configuration file"


parser = ArghParser(version=pkg_resources.get_distribution("awstools").version)

parser.add_argument('--config', default=None, help=HELP_CFG)
parser.add_argument('--settings', default=None, help=HELP_SETTINGS)

parser.add_commands([
    cloudformation.ls,
    cloudformation.create,
    cloudformation.update,
    cloudformation.batch_update,
    cloudformation.delete,
    cloudformation.info,
    cloudformation.outputs,
    cloudformation.resources,
    cloudformation.events,
    cloudformation.activities,

    cloudformation.as_limit,
    cloudformation.as_capacity,
    cloudformation.as_stop,
    cloudformation.as_start,
])

parser.dispatch(completion=False)
